### ISSUE TITLE
Server crashes if player disconnects during game

### ISSUE THREAD

**Issue by bearbob** [bearbob/cheat-cooperate#5]
If a player disconnects during a running game and the remaining players try to continue, the server crashes (see log). This might also happen during other state transitions.

```
cheat-cooperate/src/server/gamestate.js:126
    if(!partner.cooperate) {
                ^
TypeError: Cannot read property 'cooperate' of undefined
    at cheat-cooperate/src/server/gamestate.js:126:17
    at Array.forEach (<anonymous>)
    at Object.calculateResults (cheat-cooperate/src/server/gamestate.js:119:13)
    at Object.sendDecision (cheat-cooperate/src/server/communication.js:50:8)
    at Socket.<anonymous> (cheat-cooperate/index.js:56:19)
    at Socket.emit (events.js:310:20)
    at cheat-cooperate/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by bearbob** [comment]
Maybe it would be best to send an error message if a player disconnects from a running game and close the game room along with its players.
